name: Build Container FCM

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "VMC/fcm/**"
  push:
    branches:
      - main
    paths:
      - "VMC/fcm/**"

jobs:
  fcm:
    uses: ./.github/workflows/container.yml
    with:
      image: "fcm"

  fcm_x86:
    uses: ./.github/workflows/container_x86_64.yml
    with:
      image: "fcm"
      context_path: "VMC/fcm"
